### ISSUE TITLE
Seg fault thrown when processing some empty chromosomes 

### ISSUE THREAD

**Issue by AndyMenzies** [cancerit/cgpBigWig#10]
Think this is a fault with the underlying libBigWig library

Sparsely populated data can sometimes throw a segfault.  In this instance its found processing Rat Rnor_5.0 chromosome 2 that contains no reads.  Interesting in that chromosome 3 also contained no reads but would process correctly.

**Comment by AndyMenzies** [comment]
On further investigation I'm not so sure its a libBigWig problem.

I can create 2 bam files that contains a full rat header, one with 20 reads from chr1 and the other with 20 reads from chr2.

basic conversions work for both files

```
bam2bw -i chr1reads.bam 
bam2bw -i chr2reads.bam 
```

conversions including the -z switch also both work

```
bam2bw -z -i chr1reads.bam -r rat_genome.fa
bam2bw -z -i chr2reads.bam -r rat_genome.fa
```

however if I start specifying coordinate ranges it starts breaking

`bam2bw -c 2:1-285068071 -z -i chr1reads.bam -r rat_genome.fa`

throws a segfault, while the other bam file works.

If I use another whole chromosome segment, 9:1-121549591 both bam files process normally

I'm stumped.

**Comment by ghost** [comment]
I have submitted a suggested patch to libBigWig
https://github.com/dpryan79/libBigWig/issues/26

Awaiting reply.
