### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by lmy06** [cancerit/cgpBigWig#13]
I need cgpBigWig to install nearly all the other tools that we'd like to use but I'm running into installation issues.
Using version 0.4.3,I get this when running setup.sh

./setup.sh  /home/lmy/tools/cgpBigWig/
Max compilation CPUs set to 6
Get htslib ... already staged ...
Building htslib ... previously installed ...
Building libBigWig ... previously installed ...
Building cgpBigWig ...make: Entering directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'
clean
rm -f ./*.o *~ ../bin/bam2bedgraph ../bin/bam2bw ../bin/bg2bw ../bin/bam2bwbases ../bin/bwjoin ../bin/detectExtremeDepth ../bin/bwcat ./tests/tests_log ./c_tests/utils_tests ./*.gcda ./*.gcov ./*.gcno *.gcda *.gcov *.gcno ./c_tests/*.gcda ./c_tests/*.gcov ./c_tests/*.gcno
rm -rf ./htslib_tmp ../bin
make: Leaving directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'
make: Entering directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'
clean
rm -f ./*.o *~ ../bin/bam2bedgraph ../bin/bam2bw ../bin/bg2bw ../bin/bam2bwbases ../bin/bwjoin ../bin/detectExtremeDepth ../bin/bwcat ./tests/tests_log ./c_tests/utils_tests ./*.gcda ./*.gcov ./*.gcno *.gcda *.gcov *.gcno ./c_tests/*.gcda ./c_tests/*.gcov ./c_tests/*.gcno
rm -rf ./htslib_tmp ../bin
mkdir ../bin
mkdir ./htslib_tmp
#Do some magic to ensure we compile with the static libhts.a rather than libhts.so
ln -s /home/lmy/tools/source/cgpBigWig-0.4.3/install_tmp/htslib/libhts.a ./htslib_tmp/libhts.a
gcc -O3 -DVERSION='"0.4.2"' -g -Wall -I/home/lmy/tools/cgpBigWig/include -I/home/lmy/tools/source/cgpBigWig-0.4.3/install_tmp/htslib/ -rdynamic -c bam_access.c  -o bam_access.o

#In file included from bam_access.c:36:
**bam_access.h:38:20: error: bigWig.h: No such file or directory
In file included from bam_access.c:36:
bam_access.h:47: error: expected specifier-qualifier-list before ‘bigWigFile_t’
bam_access.h:67: error: expected ‘)’ before ‘*’ token
bam_access.c:38: error: expected ‘)’ before ‘*’ token
bam_access.c: In function ‘process_bam_region_bases’:
bam_access.c:240: warning: initialization makes pointer from integer without a cast
bam_access.c:240: warning: unused variable ‘contig’
bam_access.c: In function ‘process_bam_region’:
bam_access.c:340: warning: initialization makes pointer from integer without a cast
bam_access.c:340: warning: unused variable ‘contig’
make: *** [bam_access.o] Error 1
make: Leaving directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'**
Any hints would be welcome, I'm not good at C programming.

**Comment by ghost** [comment]
Hi @lmy06, 

From the first warning it appears that cgpBigWig can't see the libBigWig library. 

Firstly could you try installing again after removing the `/home/lmy/tools/source/cgpBigWig-0.4.3/install_tmp` directory please?

This will rebuild libBigWig before cgpBigWig. Let me know if this works. If not, the output from the fresh installation process may be useful in diagnosing the problem.

**Comment by lmy06** [comment]
hi @drjsanger ，
I tried, it still won't work.
The output is too long and the upside looks normal to me, so I just copy the rest output:

Building cgpBigWig ...make: Entering directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'
clean
rm -f ./*.o *~ ../bin/bam2bedgraph ../bin/bam2bw ../bin/bg2bw ../bin/bam2bwbases ../bin/bwjoin ../bin/detectExtremeDepth ../bin/bwcat ./tests/tests_log ./c_tests/utils_tests ./*.gcda ./*.gcov ./*.gcno *.gcda *.gcov *.gcno ./c_tests/*.gcda ./c_tests/*.gcov ./c_tests/*.gcno
rm -rf ./htslib_tmp ../bin
make: Leaving directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'
make: Entering directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'
clean
rm -f ./*.o *~ ../bin/bam2bedgraph ../bin/bam2bw ../bin/bg2bw ../bin/bam2bwbases ../bin/bwjoin ../bin/detectExtremeDepth ../bin/bwcat ./tests/tests_log ./c_tests/utils_tests ./*.gcda ./*.gcov ./*.gcno *.gcda *.gcov *.gcno ./c_tests/*.gcda ./c_tests/*.gcov ./c_tests/*.gcno
rm -rf ./htslib_tmp ../bin
mkdir ../bin
mkdir ./htslib_tmp
#Do some magic to ensure we compile with the static libhts.a rather than libhts.so
ln -s /home/lmy/tools/source/cgpBigWig-0.4.3/install_tmp/htslib/libhts.a ./htslib_tmp/libhts.a
gcc -O3 -DVERSION='"0.4.2"' -g -Wall -I/home/lmy/tools/cgpBigWig/include -I/home/lmy/tools/source/cgpBigWig-0.4.3/install_tmp/htslib/ -rdynamic -c bam_access.c  -o bam_access.o
bam_access.c: In function ‘process_bam_region_bases’:
bam_access.c:240: warning: initialization makes pointer from integer without a cast
bam_access.c:240: warning: unused variable ‘contig’
bam_access.c: In function ‘process_bam_region’:
bam_access.c:340: warning: initialization makes pointer from integer without a cast
bam_access.c:340: warning: unused variable ‘contig’
gcc -O3 -DVERSION='"0.4.2"' -g -Wall -I/home/lmy/tools/cgpBigWig/include -I/home/lmy/tools/source/cgpBigWig-0.4.3/install_tmp/htslib/ -rdynamic -c utils.c  -o utils.o
utils.c: In function ‘parseRegionString’:
utils.c:103: warning: pointer targets in passing argument 2 of ‘hts_parse_reg’ differ in signedness
/home/lmy/tools/cgpBigWig/include/htslib/hts.h:509: note: expected ‘int *’ but argument is of type ‘uint32_t *’
utils.c:103: warning: pointer targets in passing argument 3 of ‘hts_parse_reg’ differ in signedness
/home/lmy/tools/cgpBigWig/include/htslib/hts.h:509: note: expected ‘int *’ but argument is of type ‘uint32_t *’
utils.c:108: warning: return makes integer from pointer without a cast
gcc -O3 -DVERSION='"0.4.2"' -g -Wall -I/home/lmy/tools/cgpBigWig/include -I/home/lmy/tools/source/cgpBigWig-0.4.3/install_tmp/htslib/ -rdynamic ./bam2bedgraph.c ./bam_access.o ./utils.o -L./htslib_tmp -lhts -lpthread -lz -lm -ldl -o ../bin/bam2bedgraph
./bam2bedgraph.c: In function ‘main’:
./bam2bedgraph.c:170: warning: passing argument 2 of ‘process_bam_region’ from incompatible pointer type
./bam_access.h:61: note: expected ‘bw_func_reg’ but argument is of type ‘int (*)(uint32_t,  uint32_t,  int,  const struct bam_pileup1_t *, void *)’
gcc -O3 -DVERSION='"0.4.2"' -g -I/home/lmy/tools/cgpBigWig/include -I/home/lmy/tools/source/cgpBigWig-0.4.3/install_tmp/htslib/ -rdynamic -Wall ./bam2bw.c ./bam_access.o ./utils.o -L./htslib_tmp -L/home/lmy/tools/cgpBigWig/lib -lBigWig -lz -lcurl -lm -lgnutls -ltasn1 -lhogweed -lnettle -lgmp -lp11-kit -lhts -lpthread -lz -lm -ldl -o ../bin/bam2bw
./bam2bw.c: In function ‘main’:
./bam2bw.c:344: warning: initialization makes pointer from integer without a cast
/usr/bin/ld: cannot find -lgnutls
collect2: ld returned 1 exit status
make: *** [../bin/bam2bw] Error 1
make: Leaving directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'

**Comment by lmy06** [comment]
hi @drjsanger ，
I tried, it still won't work.
The output is too long and the upside looks normal to me, so I just copy the rest output:

Building cgpBigWig ...make: Entering directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'
clean
rm -f ./*.o *~ ../bin/bam2bedgraph ../bin/bam2bw ../bin/bg2bw ../bin/bam2bwbases ../bin/bwjoin ../bin/detectExtremeDepth ../bin/bwcat ./tests/tests_log ./c_tests/utils_tests ./*.gcda ./*.gcov ./*.gcno *.gcda *.gcov *.gcno ./c_tests/*.gcda ./c_tests/*.gcov ./c_tests/*.gcno
rm -rf ./htslib_tmp ../bin
make: Leaving directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'
make: Entering directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'
clean
rm -f ./*.o *~ ../bin/bam2bedgraph ../bin/bam2bw ../bin/bg2bw ../bin/bam2bwbases ../bin/bwjoin ../bin/detectExtremeDepth ../bin/bwcat ./tests/tests_log ./c_tests/utils_tests ./*.gcda ./*.gcov ./*.gcno *.gcda *.gcov *.gcno ./c_tests/*.gcda ./c_tests/*.gcov ./c_tests/*.gcno
rm -rf ./htslib_tmp ../bin
mkdir ../bin
mkdir ./htslib_tmp
#Do some magic to ensure we compile with the static libhts.a rather than libhts.so
ln -s /home/lmy/tools/source/cgpBigWig-0.4.3/install_tmp/htslib/libhts.a ./htslib_tmp/libhts.a
gcc -O3 -DVERSION='"0.4.2"' -g -Wall -I/home/lmy/tools/cgpBigWig/include -I/home/lmy/tools/source/cgpBigWig-0.4.3/install_tmp/htslib/ -rdynamic -c bam_access.c  -o bam_access.o
bam_access.c: In function ‘process_bam_region_bases’:
bam_access.c:240: warning: initialization makes pointer from integer without a cast
bam_access.c:240: warning: unused variable ‘contig’
bam_access.c: In function ‘process_bam_region’:
bam_access.c:340: warning: initialization makes pointer from integer without a cast
bam_access.c:340: warning: unused variable ‘contig’
gcc -O3 -DVERSION='"0.4.2"' -g -Wall -I/home/lmy/tools/cgpBigWig/include -I/home/lmy/tools/source/cgpBigWig-0.4.3/install_tmp/htslib/ -rdynamic -c utils.c  -o utils.o
utils.c: In function ‘parseRegionString’:
utils.c:103: warning: pointer targets in passing argument 2 of ‘hts_parse_reg’ differ in signedness
/home/lmy/tools/cgpBigWig/include/htslib/hts.h:509: note: expected ‘int *’ but argument is of type ‘uint32_t *’
utils.c:103: warning: pointer targets in passing argument 3 of ‘hts_parse_reg’ differ in signedness
/home/lmy/tools/cgpBigWig/include/htslib/hts.h:509: note: expected ‘int *’ but argument is of type ‘uint32_t *’
utils.c:108: warning: return makes integer from pointer without a cast
gcc -O3 -DVERSION='"0.4.2"' -g -Wall -I/home/lmy/tools/cgpBigWig/include -I/home/lmy/tools/source/cgpBigWig-0.4.3/install_tmp/htslib/ -rdynamic ./bam2bedgraph.c ./bam_access.o ./utils.o -L./htslib_tmp -lhts -lpthread -lz -lm -ldl -o ../bin/bam2bedgraph
./bam2bedgraph.c: In function ‘main’:
./bam2bedgraph.c:170: warning: passing argument 2 of ‘process_bam_region’ from incompatible pointer type
./bam_access.h:61: note: expected ‘bw_func_reg’ but argument is of type ‘int (*)(uint32_t,  uint32_t,  int,  const struct bam_pileup1_t *, void *)’
gcc -O3 -DVERSION='"0.4.2"' -g -I/home/lmy/tools/cgpBigWig/include -I/home/lmy/tools/source/cgpBigWig-0.4.3/install_tmp/htslib/ -rdynamic -Wall ./bam2bw.c ./bam_access.o ./utils.o -L./htslib_tmp -L/home/lmy/tools/cgpBigWig/lib -lBigWig -lz -lcurl -lm -lgnutls -ltasn1 -lhogweed -lnettle -lgmp -lp11-kit -lhts -lpthread -lz -lm -ldl -o ../bin/bam2bw
./bam2bw.c: In function ‘main’:
./bam2bw.c:344: warning: initialization makes pointer from integer without a cast
/usr/bin/ld: cannot find -lgnutls
collect2: ld returned 1 exit status
make: *** [../bin/bam2bw] Error 1
make: Leaving directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'

**Comment by ghost** [comment]
Looks like you're missing the gnutls library:

`/usr/bin/ld: cannot find -lgnutls collect2: ld returned 1 exit status make`

Please let me know if the installation still fails after you've added gnutls to your system.

**Comment by ghost** [comment]
@lmy06 Did this solve your issue?

**Comment by lmy06** [comment]
@drjsanger Sorry for the late raply.
./setup.sh /home/lmy/tools/cgpBigWig-0.4.3
Max compilation CPUs set to 6
Get htslib ... already staged ...
Building htslib ... previously installed ...
Building libBigWig ... previously installed ...
Building cgpBigWig ...make: Entering directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'
clean
rm -f ./*.o *~ ../bin/bam2bedgraph ../bin/bam2bw ../bin/bg2bw ../bin/bam2bwbases ../bin/bwjoin ../bin/detectExtremeDepth ../bin/bwcat ./tests/tests_log ./c_tests/utils_tests ./*.gcda ./*.gcov ./*.gcno *.gcda *.gcov *.gcno ./c_tests/*.gcda ./c_tests/*.gcov ./c_tests/*.gcno
rm -rf ./htslib_tmp ../bin
make: Leaving directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'
make: Entering directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'
clean
rm -f ./*.o *~ ../bin/bam2bedgraph ../bin/bam2bw ../bin/bg2bw ../bin/bam2bwbases ../bin/bwjoin ../bin/detectExtremeDepth ../bin/bwcat ./tests/tests_log ./c_tests/utils_tests ./*.gcda ./*.gcov ./*.gcno *.gcda *.gcov *.gcno ./c_tests/*.gcda ./c_tests/*.gcov ./c_tests/*.gcno
rm -rf ./htslib_tmp ../bin
mkdir ../bin
mkdir ./htslib_tmp
#Do some magic to ensure we compile with the static libhts.a rather than libhts.so
ln -s /home/lmy/tools/source/cgpBigWig-0.4.3/install_tmp/htslib/libhts.a ./htslib_tmp/libhts.a
gcc -O3 -DVERSION='"0.4.2"' -g -Wall -I/hwfssz1/ST_CANCER/CGR/USER/leimengyue/tools/cgpBigWig-0.4.3/include -I/home/lmy/tools/source/cgpBigWig-0.4.3/install_tmp/htslib/ -rdynamic -c bam_access.c  -o bam_access.o
**_In file included from bam_access.c:36:
bam_access.h:38:20: error: bigWig.h: No such file or directory
In file included from bam_access.c:36:
bam_access.h:47: error: expected specifier-qualifier-list before ‘bigWigFile_t’
bam_access.h:67: error: expected ‘)’ before ‘*’ token
bam_access.c:38: error: expected ‘)’ before ‘*’ token
bam_access.c: In function ‘process_bam_region_bases’:
bam_access.c:240: warning: initialization makes pointer from integer without a cast
bam_access.c:240: warning: unused variable ‘contig’
bam_access.c: In function ‘process_bam_region’:
bam_access.c:340: warning: initialization makes pointer from integer without a cast
bam_access.c:340: warning: unused variable ‘contig’
make: *** [bam_access.o] Error 1
make: Leaving directory `/home/lmy/tools/source/cgpBigWig-0.4.3/c'_**

I'm not sure what's wrong now??

**Comment by ghost** [comment]
```
bam_access.h:38:20: error: bigWig.h: No such file or directory In file included from bam_access.c:36:
```
This implies that cgpBigWig cannot see the libBigWig header files. 

Can you `ls /home/lmy/tools/cgpBigWig-0.4.3/include`  for me please

**Comment by isidroc** [comment]
Hello drjsanger,

I am trying to install cgpBigWig in Linux version 2.6.32-642.3.1.el6.x86_64 (mockbuild@worker1.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Tue Jul 12 18:30:56 UTC 2016

I get the following error. I think that lgnutls is not seen for some reason. Have you experienced this error before? 
Thanks


./bam2bw.c:338:16: warning: ‘chromList’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   chromList_t *chromList = NULL;
                ^
/usr/bin/ld: cannot find -lgnutls
collect2: error: ld returned 1 exit status
make: *** [../bin/bam2bw] Error 1
make: Leaving directory `/n/data1/hms/dbmi/park/icortes/toto/cgpBigWig-0.4.4/c'

**Comment by ghost** [comment]
Is libgnutls installed by default on your system or do you need to install it? 
`ldconfig -p | grep libgnutls` should tell you

**Comment by isidroc** [comment]
Apparently it is...
(myvirtualenv)[ic71@pit ]$ ldconfig -p | grep libgnutls
	libgnutlsxx.so.26 (libc6,x86-64) => /usr/lib64/libgnutlsxx.so.26
	libgnutls.so.26 (libc6,x86-64) => /usr/lib64/libgnutls.so.26
	libgnutls-extra.so.26 (libc6,x86-64) => /usr/lib64/libgnutls-extra.so.26

Any idea? Thanks!

**Comment by ghost** [comment]
@isidroc @lmy06  I've just tried to install on Centos 7 and it required gnutls-devel rather than just gnutls (installed via yum). Installing this may work for you?

**Comment by isidroc** [comment]
Thanks for your reply. We finally created some symbolic links and modified the Makefile to make it work. Thanks!

**Comment by ghost** [comment]
@isidroc Could you let me know what you had to modify please? It may help me make this installation more robust in future

**Comment by isidroc** [comment]
We did the following for some of the dynamic libraries, so they could be found
ln -s /usr/lib64/libtasn1.so.3.1.6 libtasn1.so

**Comment by jungminchoilab** [comment]
Hi @isidroc and @drjsanger,

I think I am experiencing the same issues. Could you please share how you modified the makefile (setup.sh?) file.

Thank you for your time,
Jungmin

```
/ycga-gpfs/apps/hpc/software/binutils/2.27-GCCcore-6.3.0/bin/ld.gold: error: cannot find -lgnutls
/ycga-gpfs/apps/hpc/software/binutils/2.27-GCCcore-6.3.0/bin/ld.gold: error: cannot find -ltasn1
/ycga-gpfs/apps/hpc/software/binutils/2.27-GCCcore-6.3.0/bin/ld.gold: error: cannot find -lhogweed
/ycga-gpfs/apps/hpc/software/binutils/2.27-GCCcore-6.3.0/bin/ld.gold: error: cannot find -lnettle
/ycga-gpfs/apps/hpc/software/binutils/2.27-GCCcore-6.3.0/bin/ld.gold: error: cannot find -lp11-kit
```

```
(vir_env) [jc2545@c15n04 cgpBigWig-1.0.0]$ ldconfig -p | grep libgnutls
	libgnutls.so.28 (libc6,x86-64) => /usr/lib64/libgnutls.so.28
	libgnutls.so.28 (libc6) => /lib/libgnutls.so.28
	libgnutls-dane.so.0 (libc6,x86-64) => /usr/lib64/libgnutls-dane.so.0
```

**Comment by ghost** [comment]
@jungminchoi Which operating system are you using? 
It looks like you are missing a few packages, do they all exist without the `.so` symlink or only libgnutls? 
[INSTALL.md](https://github.com/cancerit/cgpBigWig/blob/master/INSTALL.md) gives the packages required for various OSs.

**Comment by jungminchoilab** [comment]
Thanks for your prompt response! I am trying to install this on the cluster server.
It seems like they all exist. It will be great if you can provide help on modifying the setup.sh file.



```
(vir_env) [jc2545@c15n04 cgpBigWig-1.0.0]$ ldconfig -p | grep libtasn1
	libtasn1.so.6 (libc6,x86-64) => /usr/lib64/libtasn1.so.6
	libtasn1.so.6 (libc6) => /lib/libtasn1.so.6
(vir_env) [jc2545@c15n04 cgpBigWig-1.0.0]$ ldconfig -p | grep libhogweed
	libhogweed.so.2 (libc6,x86-64) => /usr/lib64/libhogweed.so.2
	libhogweed.so.2 (libc6) => /lib/libhogweed.so.2
(vir_env) [jc2545@c15n04 cgpBigWig-1.0.0]$ ldconfig -p | grep libnettle
	libnettle.so.4 (libc6,x86-64) => /usr/lib64/libnettle.so.4
	libnettle.so.4 (libc6) => /lib/libnettle.so.4
(vir_env) [jc2545@c15n04 cgpBigWig-1.0.0]$ ldconfig -p | grep libp11-kit
	libp11-kit.so.0 (libc6,x86-64) => /usr/lib64/libp11-kit.so.0
	libp11-kit.so.0 (libc6) => /lib/libp11-kit.so.0
```

**Comment by ghost** [comment]
Your cluster server may have one of many operating systems installed, what does running `uname -a`  when on a server machine give you and possibly `lsb_release -a`?

Interesting that none of them have the `*.so` symlink generated. Is it possible that these aren't the dev packages required to build against and are just the libraries. Do you have permissions to install to the cluster? 

Perhaps it may be easier to use our docker version? See [quay.io](https://quay.io/repository/wtsicgp/dockstore-cgpbigwig), [dockstore](https://dockstore.org/tools) , and the project they're built from [dockstore-cgpbigwig](https://github.com/cancerit/dockstore-cgpbigwig).

**Comment by jungminchoilab** [comment]
Thanks! I am getting this.
```
Linux c15n04.ruddle.hpc.yale.internal 3.10.0-514.32.3.el7.x86_64 #1 SMP Thu Sep 21 04:23:20 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Unfortunately, I do not have permissions to install. I will ask the admin if they can generate the symlinks.

**Comment by lz6063** [comment]
I installed PCAP, vcftools, and alleleCounts and at the final step to setup ascat.R.. BUT it still shows 
PREREQUISITE: Please install PCAP-core before proceeding:
  https://github.com/ICGC-TCGA-PanCancer/PCAP-core/releases

Any ideas?

**Comment by ghost** [comment]
@lz6063 I believe you need the newer version of PCAP-core, here:
https://github.com/cancerit/PCAP-core/releases

**Comment by lz6063** [comment]
do you mean version 4.3.5

**Comment by lz6063** [comment]
Ok,  I tried the newer version but ran into issue showing 

#Failed test 'No tests run for subtest "external process handling"'

I am not sure what is the best way to go from here. Last time I did mange to install all components (PCAP, vcftool, R etc) before setup ascat.R. And I FOLLOWED the tutorial step by step in the published protocal:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6097604/ 

So I wonder if there are a docker image to simply the pre-requiste step before install ascat.R or
is there any tips on address the complain I see before: PREREQUISITE: Please install PCAP-core before proceeding:

Thanks!

**Comment by keiranmraine** [comment]
@lz6063 the container https://quay.io/repository/wtsicgp/dockstore-cgpwgs has ascatNgs within it and is available for general use.  The docs on the corresponding github repo indicate how you can use this container under docker or singularity.

Please note the docs for this are on the [wiki](https://github.com/cancerit/dockstore-cgpwgs/wiki) pages and they only reference a composite wrapper, however you can replace the `ds-cgpwgs.pl ...` program with `ascat.pl -h` to see the usage

**Comment by lzbot96** [comment]
The docker version works. Thank you.
