### ISSUE TITLE
install ascatNgs-3.0.3 failure

### ISSUE THREAD

**Issue by lz6063** [cancerit/cgpBigWig#31]
I am trying to finish setup ascat after successfully install of PCAP, cgpVCF, alleleCount.

However the setup complain the following:

PREREQUISITE: Please install PCAP-core before proceeding:
  https://github.com/ICGC-TCGA-PanCancer/PCAP-core/releases

**Comment by keiranmraine** [comment]
This is not the ascatNgs project
