### ISSUE TITLE
bwjoin normalization

### ISSUE THREAD

**Issue by rspreafico-vir** [cancerit/cgpBigWig#35]
Hi there,

a use case for bwjoin could be to create a consensus track from multiple replicates. In that case, it would be pretty useful to be able to set weights/normalization factors for each replicate. This is important when the overall coverage in bigwig files has not been normalized, and so each bigwig file comes with different total coverage, which could make the contribution of replicates very deeply sequenced much higher than replicates more shallowly sequenced. 

It would be great to be able to choose how to join bigwig files, with 3 options in my mind:
- no correction for coverage. Replicates with more coverage will have more weight on the joined product.
- automatic correction for coverage such that each replicates has identical weight - that is, normalizaiton factors would be automatically computed by bwjoin
- manual correction - the user specifies weights for each replicate

**Comment by keiranmraine** [comment]
Hi,

`bwjoin` is intended for merging per-contig bigwig files from 1 experiment (merged lanes of sequencing) into a sample specific genome-wide bigwig file.  Specifically intended to allow per-contig parallelisation of bigwig generation:

```
[N * bam2bw] -> bwjoin
```

It is not intended for merging multiple datasets with the same contigs together, that would be a new program.

It is an interesting idea, but at this time I do not believe our funding users have this requirement.  

As always we are happy to review pull-requests and contributions.

Regards,
Keiran
