### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by skillcoyne** [cancerit/cgpBigWig#6]
I need cgpBigWig to install nearly all the other tools that we'd like to use but I'm running into installation issues.

Using version 0.3.0 after getting all the ubuntu libraries installed I get this when running setup.sh

In file included from bam_access.c:36:
bam_access.h:38:20: error: bigWig.h: No such file or directory
In file included from bam_access.c:36:
bam_access.h:47: error: expected specifier-qualifier-list before ‘bigWigFile_t’
bam_access.h:67: error: expected ‘)’ before ‘*’ token
bam_access.c:38: error: expected ‘)’ before ‘*’ token
make: *** [bam_access.o] Error 1

Any hints would be welcome, I'm not a C programmer.

**Comment by keiranmraine** [comment]
Cab you check further up the log please, it looks like it may have failed to get and unpack the libBigWig archive.

**Comment by kaji331** [comment]
I got errors for installation.

./bam2bedgraph.c: 在函数‘main’中: (chinese 在函数 = in function)
./bam2bedgraph.c:170: 警告：传递‘process_bam_region’的第 2 个参数时在不兼容的指针类型间转换 
(warning:transporting 'process_bam_region' second parameter has invalid pointer typer change)
gcc -O3 -DVERSION='"0.3.0"' -g -I/share/home/xierf/Yang_L/cgpPindel/cgpBigWig-0.3.0/final/include -I/share/home/xierf/Yang_L/cgpPindel/cgpBigWig-0.3.0/install_tmp/htslib/ -rdynamic -Wall ./bam2bw.c ./bam_access.o ./utils.o -L./htslib_tmp -L/share/home/xierf/Yang_L/cgpPindel/cgpBigWig-0.3.0/final/lib -lBigWig -lz -lcurl -lm -lgnutls -ltasn1 -lhogweed -lnettle -lgmp -lp11-kit -lhts -lpthread -lz -lm -ldl -o ../bin/bam2bw
/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld: cannot find -lgnutls
collect2: ld 返回 1 (return 1)
make: *** [../bin/bam2bw] 错误 1 (error 1)
make: Leaving directory `/share/home/xierf/Yang_L/cgpPindel/cgpBigWig-0.3.0/c'

**Comment by kaji331** [comment]
gcc 4.3.4

**Comment by ghost** [comment]
`/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld: cannot find -lgnutls`

It looks like you are missing the gnutls library.
